# Generated by Django 3.1.7 on 2021-03-09 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('is_doLens', models.BooleanField(default=False)),
                ('is_doRims', models.BooleanField(default=False)),
                ('is_doSunGlasses', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.SlugField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.SlugField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlassesRim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='glasses/')),
                ('price', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('is_sunGlasses', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.brand')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.color')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.gender')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.material')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.shape')),
            ],
        ),
    ]
