# Generated by Django 3.1.7 on 2021-03-14 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_glassesrim_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='glassesrim',
            name='title',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
